window.l_loc =  {
    'l_pl1' : 'You have not filled in the "Phone" field',
    'l_pl2' : 'You did not fill in the field "Name"',
    'l_pl3' : 'Incorrectly filled field "Name"',
    'l_pl4' : 'Phone number entered is too short',
    'l_pl5' : 'Phone number entered is too long',
    'l_pl6' : 'Unfortunately, an error occurred while creating the order, our manager will contact you',
    'l_pl7' : 'Dear customer, you have created a duplicate order. If you need to make adjustments to the original order, please wait for a call from the logistics manager and you will be able to make the necessary adjustments',
    'l_pl8' : 'Sorry, delivery to your country is not carried out',
    'l_pl9' : 'Thank you for your order, our manager will contact you shortly!',
    'l_pl10' : 'Confirm that the number is correct:',
    'l_pl11' : 'YES',
    'l_pl12' : 'NO',
    'l_pl13' : 'Attention, action!',
    'l_pl14' : 'Personally for you, and only at the moment we offer an amazing <strong>discount!</strong>',
    'l_pl15' : 'Personally for you, and only at the moment we offer a stunning <strong><span class="green-text">discount!<span/><strong/>',
    'l_pl16' : 'Make an order right now and take advantage of the conditions of this promotion',
    'l_pl17' : 'promotional offers',
    'l_pl18' : 'person viewing this page',
    'l_pl19' : 'Attention! Last offer left',
    'l_pl20' : 'Telephone:',
    'l_pl21' : 'Example:',
    'l_pl22' : 'Current price:',
    'l_pl23' : 'Current </br> price:',
    'l_pl24' : 'Order and save {{discount_price}} {{currency}}',
    'l_pl25' : 'ONE SECOND!',
    'l_pl26' : 'Before you leave, we want to offer you a GIFT!',
    'l_pl27' : 'We are ready to reduce the price by {{unload_price}} {{currency}}!',
    'l_pl28' : 'To get it - click on the "Stay" button on this page',
    'l_pl29' : 'Before you leave, consider our offer!',
    'l_pl30' : 'We are ready to provide you with goods on VERY good conditions!',
    'l_pl31' : 'To consider the offer - click on the "Stay" button on this page',
    'l_pl32' : 'Request a call back',
    'l_pl33' : 'We will call you back within 1 minute!',
    'l_pl34' : 'All <strong>calls are free!</strong>',
    'l_pl35' : '<strong>Attention! </strong> In order to get a discount, dictate the promotion code to the manager: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Privacy Policy',
    'l_pl37' : 'Terms of use',
    'l_pl38' : 'I am waiting for a call',
    'l_pl39' : 'Don\'t want to wait?',
    'l_pl40' : 'left',
    'l_pl41' : 'promotional offers',
    'l_pl42' : 'promotional offers',
    'l_pl43' : 'now',
    'l_pl44' : 'Incorrectly filled field "E-mail"',
    'l_pl45' : 'Phone number',
    'l_pl46' : 'Refuse',
    'l_pl47' : 'Dear customer, if you have active orders, your personal data will be deleted within 48 hours from the moment of their execution',
    'l_pl48' : 'Refusal to process personal data',
    'l_pl49' : 'Order',
    'l_pl50' : 'Enter your name',
    'l_pl51' : 'Enter phone',
    'l_pl52' : 'FULL NAME',
    'l_pl53' : 'Invalid field "Phone"',
    'l_pl54' : 'Communication error, please refresh the page',
    'l_pl55' : 'An error has occurred',
    'l_pl56' : 'Confirm that the number is correct',
    'l_pl57' : 'January',
    'l_pl58' : 'February',
    'l_pl59' : 'March',
    'l_pl60' : 'April',
    'l_pl61' : 'May',
    'l_pl62' : 'June',
    'l_pl63' : 'July',
    'l_pl64' : 'August',
    'l_pl65' : 'September',
    'l_pl66' : 'October',
    'l_pl67' : 'November',
    'l_pl68' : 'December',
    'l_pl69' : 'sunday',
    'l_pl70' : 'monday',
    'l_pl71' : 'tuesday',
    'l_pl72' : 'wednesday',
    'l_pl73' : 'thursday',
    'l_pl74' : 'friday',
    'l_pl75' : 'saturday',
    'l_pl76' : 'Dear Customer',
    'l_pl77' : 'An error has occurred. Please try again in 24 hours.'
}